### ISSUE TITLE
Manque t-il quelque chose ?

### ISSUE THREAD

**Issue by Vadrieniel** [indilo53/fivem-esx_weedjob#1]
Bonsoir, c'est encore moi, donc voilà j'ai installer tout les scripts que tu proposais, honnêtement le skin changer c'est une tuerie :) Mais la je rencontre un problème avec le weedjob, faut t-il quelque chose en particulier pour le faire fonctionner ? Je suis à la ferme à weed mais rien ne ce passe ? Il manque un script ou autre ou je doit tout simplement en faire un job ? Merci encore.

**Comment by indilo53** [comment]
Merci :) Avez-vous ajouté le fichier sql à la base de données

**Comment by indilo53** [comment]
Y a-t-il un message d'erreur dans le log du serveur on quand vous appuyez sur F8 après être passé sur le point ?

**Comment by Vadrieniel** [comment]
Oui j'ai ajouter le .sql, il y aucune erreur dans la console f8 ni dans la console de lancement, j'ai même essayer d'ajouter le script missiontext pensant qu'il était manquant mais rien n'a changer.

**Comment by indilo53** [comment]
Voyez-vous le marqueur vert a la ferme ?

**Comment by indilo53** [comment]
est-il bien ajoute dans le yml ?

**Comment by Vadrieniel** [comment]
Je m'en vais acheter une corde ... J'avais oublier de le mettre dans le yml faut que j'arrête pour aujourd'hui :s Désolé de t'avoir déranger pour rien... Merci encore pour ton aide.

**Comment by indilo53** [comment]
Pas de problème bonne soirée :)
