### ISSUE TITLE
Petite question

### ISSUE THREAD

**Issue by Vadrieniel** [indilo53/fivem-esx_weedjob#2]
Hello, c'est encore moi :p En faite j'aimerais bien créer d'autre métier comme brasseur, fermier, mineur d'autre truc du style, mais je voulais me baser sur le weedjob car celui de police demande trop de modification, donc j'aurais voulu savoir, le weedjob est t-il considérer comme un job accessible avec la commande /setjob * ** * ?

Voilà merci à toi.

Ah oui bien entendu, c'est une demande, si tu ne souhaite pas que je le modifie je respecterais ton choix, dans tout les cas c'est toi qui reste l'auteur je ne compte pas te plagier :)

**Comment by indilo53** [comment]
C'est une très bonne idée. Le weedjob est un job officieux, pas besoin de /setjob. Si tu veux faire un job officiel, je te conseille d'attendre mes prochains scripts (abatteur de poulet, pêcheur) pour voir comment faire un vestiaire / vérifier que le joueur a bien tel job etc... Et puis on pourra toujours se contacter sur teamspeak ou discord pour que tu démarre sur une bonne base. J'ai également un cokejob et un methjob à sortir donc pas la peine de te casser la tête sur ces drogues. J'ai également un pôle-emploi mais un petit bug à résoudre avant de le mettre en ligne.

**Comment by Vadrieniel** [comment]
Ok pas de soucis je vais attendre :) Par contre je rencontre quelque problème avec le job police je créer une nouvelle question ou je te les poste ici ?

**Comment by indilo53** [comment]
Crée une nouvelle question dans esx_policejob
