### ISSUE TITLE
Hi dude. :)

### ISSUE THREAD

**Issue by SmokeyKatevin** [indilo53/fivem-esx_weedjob#4]
SOLVED

Merci d'avoir lu. :)

**Comment by SmokeyKatevin** [comment]
J'ai résolu le problème désolé du dérangement, et merci du partage.

**Comment by TonTonSheitan** [comment]
Salut smokey tu as réussi a faire plusieurs drogue dans le mémé fichier ? 

car moi quand je veut faire plusieurs drogue tout fonctionne très bien sauf la touche en bas a droite qui indique se con farm c'est écrit "undefined" et je voit pas du tout de ou sa peut venir :/

Si jamais tu as la solution Merci :)

**Comment by SmokeyKatevin** [comment]
Non je les ai faites en séparée :)
