### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ungarscool1** [indilo53/fivem-esx_weedjob#5]
Bonjour, tu utilise quel menu inventaire pour les items ?

**Comment by dylan48700** [comment]
Salut je sais pas si tu as résolu ton problème d.inventairé mais moi je récolte bien mais sa ne s’affiche pas dans mon inventaire ...  si tu a régler ton problème peut tu me dire qu’elle inventaire tu utilise ? 

Merci

**Comment by ungarscool1** [comment]
Salut,
Non je n'ai pas résolu mon problème, mais si tu regarde dans la db sa te donne quoi ?

**Comment by dylan48700** [comment]
Comment ça ?

**Comment by ungarscool1** [comment]
au niveau des items est-ce que tu as mis le SQL, sinon je ne sais pas

**Comment by dylan48700** [comment]
Oui oui j’ai mis le sql, quand je vais ingame, j’ai bien le bleaps. Je fais entrer sa me dit ‘’ ramassage en cours ‘’ mais rien ne s’ajoute dans mon inventaire

**Comment by ungarscool1** [comment]
Et quand tu regarde dans la DB sur l'inventaire des joueurs tu vois l'item ou non ?

**Comment by dylan48700** [comment]
Oui oui, je comprend pas :(

**Comment by ungarscool1** [comment]
fait un dump de ta base de donnée avec toutes les données dedans, comme ça je regarde

**Comment by dylan48700** [comment]
Après je me suis servi dWeedJob comme base pour créer un trafic d’arme donc weed a été remplacer par arme et weedpooch par caissArme le problème émeut venir de la ? Sachant que dans le jeu tout est ok sauf l’affichage dans l’inventaire

**Comment by dylan48700** [comment]
[fxserver.zip](https://github.com/indilo53/fivem-esx_weedjob/files/1380274/fxserver.zip)

**Comment by ungarscool1** [comment]
Ta bien connecter la ressource avec la base de donnée ?

**Comment by dylan48700** [comment]
Oui j'ai bien mis le sstart dans mon server.cfg

**Comment by dylan48700** [comment]
![capture](https://user-images.githubusercontent.com/32740071/31512766-65a288f4-af8c-11e7-8be1-50d027dc8817.JPG)

**Comment by ungarscool1** [comment]
Ta tout les fichiers [indilo53/fivem-es_extended](https://github.com/indilo53/fivem-es_extended), si ce n'est pas ça je suis désolé mais je ne vais pouvoir t'aidé

**Comment by dylan48700** [comment]
Oui j'ai bien tous installer... tampis je te remercie d'avoir voulu m'aider c'est très sympa de ta part !
