### ISSUE TITLE
Petit probleme depuis la maj

### ISSUE THREAD

**Issue by nlmarcio** [indilo53/fivem-esx_weedjob#7]
Bonjour, depuis que j'ai ajouter la MAJ qui vérifie le nombre de COP en ligne, il est impossible de récolter, transformer ou vendre.
Voila l'erreur afficher dans la console : 

`2017-06-11 14:25:24.0355|ERROR|CitizenMP.Server|Error executing event handler for event esx_weedjob:startHarvestWeed in resource esx_weedjob: Exception has been thrown by the target of an invocation.
2017-06-11 14:25:24.0360|ERROR|CitizenMP.Server| at [U] System.Reflection.MonoMethod.Invoke(Object obj,BindingFlags invokeAttr,Binder binder,Object[] parameters,CultureInfo culture)
2017-06-11 14:25:24.0360|ERROR|CitizenMP.Server| at [U] System.Reflection.MethodBase.Invoke(Object obj,Object[] parameters)
2017-06-11 14:25:24.0360|ERROR|CitizenMP.Server| at [U] System.Delegate.DynamicInvokeImpl(Object[] args)
2017-06-11 14:25:24.0368|ERROR|CitizenMP.Server| at [U] System.MulticastDelegate.DynamicInvokeImpl(Object[] args)
2017-06-11 14:25:24.0368|ERROR|CitizenMP.Server| at [U] System.Delegate.DynamicInvoke(Object[] args)
2017-06-11 14:25:24.0368|ERROR|CitizenMP.Server| at [U] CitizenMP.Server.Resources.ScriptEnvironment.TriggerEvent(String eventName,String argsSerialized,Int32 source)
2017-06-11 14:25:24.0368|ERROR|CitizenMP.Server|Inner exception: Object is nil.`

En désactivant les lignes suivantes dans chaque fonction, il n'y as pas de probleme : 
`	if CopsConnected < Config.RequiredCops then
		TriggerClientEvent('esx_weedjob:showNotification', source, 'Action ~r~impossible~s~, ~b~policiers~s~: ' .. CopsConnected .. '/' .. Config.RequiredCops)
		return
	end`

je suis le seul a avoir ce problème?

**Comment by ig0ne** [comment]
#Pas encore test!
Est ce que le problème ne viendrais pas de là:
```lua
local function HarvestWeed(source)

	if CopsConnected < Config.RequiredCops then
		TriggerClientEvent('esx_weedjob:showNotification', source, 'Action ~r~impossible~s~, ~b~policiers~s~: ' .. CopsConnected .. '/' .. Config.RequiredCops)
		return
	end

	SetTimeout(5000, function()

		if PlayersHarvesting[source] == true then

			TriggerEvent('esx:getPlayerFromId', source, function(xPlayer)

				local weed = xPlayer:getInventoryItem('weed')

				if weed.limit ~= -1 and weed.count >= weed.limit then
					TriggerClientEvent('esx_weedjob:showNotification', source, 'Vous ne pouvez plus ramasser de weed, votre inventaire est ~r~plein~s~')
				else
					xPlayer:addInventoryItem('weed', 1)
					HarvestWeed(source)
				end

			end)

		end
	end)
end
```
Peut être mettre ça à la place:
```lua
local function HarvestWeed(source)

	if CopsConnected < Config.RequiredCops then
		TriggerClientEvent('esx_weedjob:showNotification', source, 'Action ~r~impossible~s~, ~b~policiers~s~: ' .. CopsConnected .. '/' .. Config.RequiredCops)
		return
	else
	
		SetTimeout(5000, function()

			if PlayersHarvesting[source] == true then

				TriggerEvent('esx:getPlayerFromId', source, function(xPlayer)

					local weed = xPlayer:getInventoryItem('weed')

					if weed.limit ~= -1 and weed.count >= weed.limit then
						TriggerClientEvent('esx_weedjob:showNotification', source, 'Vous ne pouvez plus ramasser de weed, votre inventaire est ~r~plein~s~')
					else
						xPlayer:addInventoryItem('weed', 1)
						HarvestWeed(source)
					end

				end)

			end
		end)
	end
end
```

**Comment by indilo53** [comment]
As tu ajouté Config.RequiredCops = 0 dans le fichier config ? Il a été mis à jour

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nlmarcio** [comment]
Bonjour,
oui j'ai mis a jour le fichier config. et j'ai tester avec RequiredCops à 1 avec ou sans un cop de connecter sur le serveur et ça ne change rien.

pour ta partie de script a modifier, ig0ne cela fait exactement la même erreur.

Par contre j'ai remarquer que le "Config.RequiredCorps" ne renvoyait rien quand il était coté serveur, mais que coté client il parvenais bien a récupérer la valeur du fichier config.

**Comment by indilo53** [comment]
J'ai fait une maj, j'ai ajouté le config.lua au serveur je l'avais oublié
